# Generated by Django 6.0.2 on 2026-02-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rma', '0002_rename_batch_to_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaleRMARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
                ('marked_stale_at', models.DateTimeField(auto_now_add=True)),
                ('notification_sent', models.BooleanField(default=False)),
                ('resolved', models.BooleanField(default=False, help_text='Set to True when RMA moves to next state')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stale_records', to='rma.rma')),
            ],
            options={
                'verbose_name': 'Stale RMA Record',
                'verbose_name_plural': 'Stale RMA Records',
                'ordering': ['-marked_stale_at'],
            },
        ),
        migrations.CreateModel(
            name='StateTimeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('RECEIVED', 'Received'), ('DIAGNOSED', 'Diagnosed'), ('REPAIRED', 'Repaired'), ('REPLACED', 'Replaced'), ('SHIPPED', 'Shipped')], help_text='RMA state this timeout applies to', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], help_text='Priority level this timeout applies to', max_length=10)),
                ('timeout_hours', models.IntegerField(help_text='Number of hours before RMA is considered stale in this state')),
            ],
            options={
                'verbose_name': 'State Timeout Configuration',
                'verbose_name_plural': 'State Timeout Configurations',
                'ordering': ['state', 'priority'],
                'unique_together': {('state', 'priority')},
            },
        ),
    ]
