# Generated by Django 6.0.2 on 2026-02-21 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebAuthnCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.BinaryField(max_length=1024, unique=True)),
                ('public_key', models.BinaryField(max_length=1024)),
                ('sign_count', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(help_text="User-friendly name for this credential (e.g., 'MacBook Pro Touch ID', 'YubiKey 5')", max_length=100)),
                ('aaguid', models.BinaryField(blank=True, max_length=16, null=True)),
                ('transports', models.JSONField(default=list, help_text='Supported transports (usb, nfc, ble, internal)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webauthn_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'WebAuthn Credential',
                'verbose_name_plural': 'WebAuthn Credentials',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebAuthnChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.BinaryField(max_length=64)),
                ('session_key', models.CharField(max_length=100, unique=True)),
                ('is_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='User for authentication, null for registration', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_key'], name='webauthn_au_session_4c0974_idx'), models.Index(fields=['created_at'], name='webauthn_au_created_707e63_idx')],
            },
        ),
    ]
