# Generated by Django 6.0.2 on 2026-02-20 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.IntegerField(editable=False, unique=True)),
                ('state', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RECEIVED', 'Received'), ('DIAGNOSED', 'Diagnosed'), ('REPAIRED', 'Repaired'), ('REPLACED', 'Replaced'), ('SHIPPED', 'Shipped'), ('COMPLETED', 'Completed')], default='SUBMITTED', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High')], default='NORMAL', max_length=10)),
                ('serial_number', models.CharField(db_index=True, max_length=100)),
                ('first_ship_date', models.DateField(blank=True, null=True)),
                ('fault_notes', models.TextField(help_text='Issue description and fault notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rma_received_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('parts_replaced', models.TextField(blank=True)),
                ('cost_to_repair', models.CharField(blank=True, max_length=100)),
                ('tx2_mac', models.CharField(blank=True, help_text='MAC address in format XX:XX:XX:XX:XX:XX', max_length=17)),
                ('script_ran', models.BooleanField(default=False)),
                ('services_enabled', models.BooleanField(default=False)),
                ('uptime_good', models.BooleanField(default=False)),
                ('stream_good', models.BooleanField(default=False)),
                ('ship_ready', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RMAAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='rma_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='rma.rma')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RMABatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='rma',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rmas', to='rma.rmabatch'),
        ),
        migrations.CreateModel(
            name='RMAStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(blank=True, max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='rma.rma')),
            ],
            options={
                'verbose_name_plural': 'RMA state histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['serial_number'], name='rma_rma_serial__0e5690_idx'),
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['state'], name='rma_rma_state_7f5321_idx'),
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['owner'], name='rma_rma_owner_i_459126_idx'),
        ),
    ]
