# Generated by Django 6.0.2 on 2026-02-20 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # Rename the model
        migrations.RenameModel(
            old_name='RMABatch',
            new_name='RMAGroup',
        ),
        # Rename the field in RMA
        migrations.RenameField(
            model_name='rma',
            old_name='batch',
            new_name='group',
        ),
        # Update the related_name in RMAGroup
        migrations.AlterField(
            model_name='rmagroup',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rma_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
