# Generated by Django 6.0.2 on 2026-03-07 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rma', '0002_rename_batch_to_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='company_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='Company ID from USERinator (denormalized for efficient filtering)', null=True),
        ),
        migrations.AddIndex(
            model_name='rma',
            index=models.Index(fields=['company_id'], name='rma_rma_company_9c174c_idx'),
        ),
    ]
