# Generated by Django 6.0.2 on 2026-02-20 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('STATE_CHANGE', 'State Changed')], default='UPDATE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('field_name', models.CharField(blank=True, help_text='Name of the field that changed', max_length=100)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (as string)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (as string)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this change')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log Entry',
                'verbose_name_plural': 'Audit Log Entries',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-timestamp'], name='audit_audit_content_b00bcf_idx'), models.Index(fields=['user', '-timestamp'], name='audit_audit_user_id_ea8c9f_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
